"""
Recommender module for generative recommendation system.

This module implements the second stage of the recommendation pipeline,
which uses semantic IDs generated by RQ-VAE to train a T5-based recommender model.
"""

__version__ = "0.1.0"

